# Generated by Django 6.1.1 on 2026-10-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lastfm_session_key',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='lastfm_username',
            field=models.CharField(blank=True, null=True),
        ),
    ]
